---
title: "Cox ph model and m() function"
date: 2020-02-24
output: pdf_document
header-includes:
  - \usepackage{color}
fontsize: 12pt
---


**Estimator with covariates**


When there are covariates that are needed to be considered in the model to estimate the survival time, the most commonly used method is Cox PH model, by 
\begin{equation}S^{cox}(t | X = x) = S_0(t)^{\exp(\beta ^\prime x)}\end{equation}
where $x = (x_1,..,x_p)^\prime, \beta = (\beta_1,...,\beta_p)^\prime$ are vectors. Also,
\begin{equation}\lambda_T(t|x) = \lambda_{0}(t) \exp(\beta ^\prime x), \Lambda_T(t|x) = \Lambda_{0}(t) \exp(\beta ^\prime x)\end{equation}

Dikta proposed another semi-parametric estimator with consideration of covariates. 
The estimator is derivatived from the estimator generated by Stute (1993), instead of the product limit estimator from Kaplan Meier. 

The Stute estimator (which estimates $E(\phi(x,t))$): 
\begin{equation}F_0(x,t) = P(X \leq x, T \leq t) = \sum_{i=1}^n W_i \phi(x,t)\end{equation}
If we set $\phi(x,t) = I_{(X \leq x, T \leq t)}$, it leads to
\begin{equation}F_0(x,t) = \sum_{i=1}^n W_i I_{(X \leq x, T \leq t)} = \sum_{i=1}^n \big \{ \frac{\delta_i}{n - i + 1} \big[ \prod_{j = 1}^{i-1} (1 - \frac{1}{n-j + 1})^{\delta_i} \big ] \big \} I_{(X \leq x, T \leq t)}\end{equation}
where $W_i = \frac{\delta_i}{n - i + 1} \prod_{j = 1}^{i-1} (1 - \frac{1}{n-j + 1})^{\delta_i}$. 

\color{blue} Question: when $i = 1$, what is the production value? 
\color{black}

Dikta replaced $\delta_i$ with $m(t,x)$ and got
\begin{equation}S^{D3} =\sum_{i=1}^n  \big \{ \frac{m(Z_i, X_i)}{n - i + 1}  \big[ \prod_{j = 1}^{i-1} (1 - \frac{m(Z_i, X_i)}{n-j + 1})  \big] \big \} I_{(X \leq x, T \leq t)}\end{equation}
Therefore, the esimators of Cox PH model and of Dikta's model are actually  estimating different things, i.e.

\color{blue}
Cox
$$S^{cox}(t | X = x) = P(T > t | X = x)$$
Dikta 
$$S^{D3} = P(T < t, X < x) = P(T < t, X_1 < x_1, ... , X_p < x_p)$$

\color{red}

Should $S^{cox}(t | X = x)$ and $S^{D3} = P(T < t, X < x)$ close to each other? 

\color{black}

We then need some transformations. Since,
$$\begin{aligned}
 \int_{0}^t f_{T,X}(t,x) dt = & \int_{0}^t f_{T|X}(t|x) f_X(x) dt \\
 = & f_X(x)  \int_{0}^t f_{T|X}(t|x) dt \\
 = & f_X(x) P(T < T | X = x)
\end{aligned}$$
then 
<!-- $$P(T < t | X = x) = \frac{1}{f_X(x)} \int_{0}^t f_{T,X}(t,x) dt =\frac{1}{f_X(x)} \frac{\partial }{\partial t} P(T < t, X < x)$$ -->

* $P(T < t | X = x) = \frac{1}{f_X(x)} \int_{0}^t f_{T,X}(t,x) dt$ 

* $f_{T,X}(t,x) = f_X(x)  \frac{\partial }{\partial t} P(T < t | X = x)$

* $\begin{aligned}F_{T,X}(t,x) =&  \int_0^x \int_0^t f_{T,X}(t,x) dt dx \\
=&   \int_0^x \int_0^t f_X(x)  \frac{\partial }{\partial t} P(T < t | X = x) dt dx \\
=& \int_0^x  f_X(x) P(T < t | X = x) dx
\end{aligned}$

Then for example, if we have one dimension covariate $X \sim N(0,1)$. The conditional distribution 
$$P(T > t | X = x) = S(t|x) = S_0(t)^{\exp(x)} = \exp(-t \times \exp(x))$$
$$P(T < t | X = x) = 1 - P(T > t | X = x) = 1 -  \exp(-t \times \exp(x))$$
$$\begin{aligned}
F_{T,X}(t,x)=& \int_0^x  f_X(x) P(T < t | X = x) dx \\
= & \int_0^x \frac{1}{\sqrt{2\pi}}\exp(-\frac{x^2}{2}) (1 -  \exp(-t \times \exp(x))) dx \\
= & \Phi(x) - \int_0^x \frac{1}{\sqrt{2\pi}}\exp(-\frac{x^2}{2}-t \exp(x)) dx
\end{aligned}$$
which does not have a close form. 

### Uniform setting

To make the calculation easy, let's try to have $X$ generated from other distributions. Suppose $X \sim UNI(0,1)$We then have 
$$\begin{aligned}
f_{T,X}(t,x) = & f_X(x) \frac{\partial }{\partial t} P(T < t | X = x) \\
= & 1 \times \exp(x) \exp(-t \times \exp(x))
\end{aligned}$$
$$F_{T,X}(t,x) = \frac{1}{\exp(x)}- \frac{1}{\exp(x)}\exp(-t \times \exp(x)) = \exp(-x) - \exp(-x-t  \exp(x))$$



