---
title: "Bootstrapping of variance"
date: 2019-11-18
output: pdf_document
---

```{R include = FALSE}
library(knitr)
library(kableExtra)


for(functions in 1){
  ##########################################
  # when x > y, 
  # x ~ exp(-x)
  # cdf F(Y | X = x): 
  
  Fc_t = function(c,x){
    c = theta*c
    x = theta*x
    res = 1 - ((2*exp(c + 1) - 2*exp(1))*(exp(c^2))*x + (-2*c*exp(c + 1) + 2*exp(1)*c + exp(1))* exp(c^2))* 
      exp(-exp(c)*x^2 + x^2 + 2*c*exp(c)*x - 2*c*x - c^2*exp(c) - exp(c))
    return(res)
  } 
  
  ##########################################
  # inverse function of F(Y | X = x):
  inverse_fct = function(a,y){
    res1 = c()
    for(i in seq(0.00001, 1, 0.1)){
      res1 = c(res1, Fc_t(i, y))
    }
    temp = seq(0.00001, 1, 0.1)[which(abs(res1 - a) == min(abs(res1 - a)))[1]]
    
    res2 = c()
    for(i in seq((temp - 0.1), (temp+0.1), 0.01)){
      res2 = c(res2, Fc_t(i, y))
    }
    temp = seq((temp - 0.1), (temp+0.1), 0.01)[which(abs(res2 - a) == min(abs(res2 - a)))[1]]
    
    res3 = c()
    for(i in seq((temp - 0.01), (temp+0.01), 0.001)){
      res3 = c(res3, Fc_t(i, y))
    }
    temp = seq((temp - 0.01), (temp+0.01), 0.001)[which(abs(res3 - a) == min(abs(res3 - a)))[1]]
    
    res4 = c()
    for(i in seq((temp - 0.001), (temp+0.001), 0.0001)){
      res4 = c(res4, Fc_t(i, y))
    }
    temp = seq((temp - 0.001), (temp+0.001), 0.0001)[which(abs(res4 - a) == min(abs(res4 - a)))[1]]
    return(temp)
  }
  
  ##########################################
  # Functions to calculate true m()
  # m function = lambda_f/lambda_h
  
  m = function(x){
    return(1/(1 + exp(theta * x)))
  }
  
  ## hazard function of observed time, calculated with tie
  lambda_H = function(t){
    i = which(abs(unique(data$time) - t) == min(abs(unique(data$time) - t)))
    if(unique(data$time)[i] > t & i > 1 ){i = i - 1}
    h = (fit_km$n.event[i] + fit_km$n.censor[i])/ fit_km$n.risk[i]
    return(h)
  }
  
  ## cumulative hazard function of observed time, calculated with tie
  Lambda_H = function(t){
    i = which(abs(unique(data$time) - t) == min(abs(unique(data$time) - t)))[1]
    if(unique(data$time)[i] > t & i > 1){i = i -1}
    HH = c()
    for(ii in 1:i){
      HH = c(HH, (fit_km$n.event[ii]+fit_km$n.censor[ii])/fit_km$n.risk[ii])
    }
    return(sum(HH))
  }
  
  ## hazard 
  lambda_F = function(t){
    h = lambda_H(t) * m(t)
    return(h)
  }
  
  ## cumulative hazard
  Lambda_F = function(t){
    i = which(abs(unique(data$time) - t) == min(abs(unique(data$time) - t)))[1]
    if(unique(data$time)[i] > t & i > 1){i = i -1}
    HH = c()
    for(ii in 1:i){
      HH = c(HH, lambda_F(unique(data$time)[ii]))
    }
    return(sum(HH))
  }
  
  ## estimate the S() with m function
  S_est = function(t){
    return(exp(-Lambda_F(t)))
  }
  
  ##########################################
  # m function (Gerhard method)
  Ri = function(t){
    return(sum(data$time <= t))
  } 
  m_est_old1 = function(t){
    res = 1
    for(i in 1:Ri(t)){
      res = res * ((n - i)/(n - i + 1))^(m(data$time[i]))
    }
    return(res)
  }
  m_est_old2 = function(t){
    res = 1
    for(i in 1:Ri(t)){
      res = res * ((n - i)/(n - i + m(data$time[i])))
    }
    return(res)
  }
  
  
}

```


```{R include = FALSE}
setwd('/Users/yaolanqiu/Desktop/NYU/Research/Survival/M variance 20191117')

theta_list = c(0.8, 1, 1.5, 2, 5)

the_est = c()
m_est = c()
m_diff = c()
em_diff = c()
qq_list = list()
eqq_list = list()
vv_list = list()
evv_list = list()

for(i in 1:5){
  names = paste('theta_2_', theta_list[i], '.RData', sep ='')
  load(names)
  
  
  # theta estimate 
  the_est = c(the_est, mean(abs(- result$theta_est )))
  hist(abs(-result$theta_est -  theta_list[i]), breaks = 50)
  
  range(-result$theta_est)
  sd(-result$theta_est)
  hist(abs(-result$theta_est -  theta_list[i]), breaks = 50)
  
  # m estimate 
  m_est = c(m_est, mean(result$m_diff))
  sd(result$m_diff)
  range(result$m_diff)
  hist(result$m_diff, breaks = 50)
  
  # mean estimation 
  m_data = data.frame(km = result$diff1, m1 = result$diff2, m2 = result$diff3, m3 = result$diff4) 
  em_data = data.frame(km = result$ediff1, m1 = result$ediff2, m2 = result$ediff3, m3 = result$ediff4) 
  
  m_diff = rbind(m_diff, apply(m_data, 2, mean))
  em_diff = rbind(em_diff, apply(em_data, 2, mean))
  
  apply(m_data[1:250, ], 2, mean)
  apply(em_data[1:250, ], 2, mean)
  
  ## 
  qq = c()
  qq = rbind(qq, apply(result$qq1,2,sd), 
             apply(result$qq2,2,sd),
             apply(result$qq3,2,sd),
             apply(result$qq4,2,sd),
             apply(result$qq5,2,sd),
             apply(result$qq6,2,sd),
             apply(result$qq7,2,sd))
  rownames(qq) = c('10th', '20th', '50th', '125th', '250th', '325th', '400th')
  colnames(qq) = c('KM', 'new m()', 'Dikta1', 'Dikta2')
  round(qq, 5)
  
  qq_list[[i]] = qq
  
  eqq = c()
  eqq = rbind(eqq, apply(result$eqq1,2,sd), 
              apply(result$eqq2,2,sd),
              apply(result$eqq3,2,sd),
              apply(result$eqq4,2,sd),
              apply(result$eqq5,2,sd),
              apply(result$eqq6,2,sd),
              apply(result$eqq7,2,sd))
  rownames(eqq) = c('10th', '20th', '50th', '125th', '250th', '325th', '400th')
  colnames(eqq) = c('KM', 'new m()', 'Dikta1', 'Dikta2')
  round(eqq, 5)
  
  eqq_list[[i]] = eqq
  
 

  vv1 = rbind(apply(result$qq1,2,sd)[2:4] / apply(result$qq1,2,sd)[1], 
              apply(result$qq2,2,sd)[2:4] / apply(result$qq2,2,sd)[1], 
              apply(result$qq3,2,sd)[2:4] / apply(result$qq3,2,sd)[1], 
              apply(result$qq4,2,sd)[2:4] / apply(result$qq4,2,sd)[1], 
              apply(result$qq5,2,sd)[2:4] / apply(result$qq5,2,sd)[1], 
              apply(result$qq6,2,sd)[2:4] / apply(result$qq6,2,sd)[1],
              apply(result$qq7,2,sd)[2:4] / apply(result$qq7,2,sd)[1])
  
  rownames(vv1) = c('10th', '20th', '50th', '125th', '250th', '325th', '400th')
  colnames(vv1) = c('new m()', 'Dikta1', 'Dikta2')
  
  round(vv1,4)
  vv_list[[i]] = vv1
  
  evv1 = rbind(apply(result$eqq1,2,sd)[2:4] / apply(result$eqq1,2,sd)[1], 
               apply(result$eqq2,2,sd)[2:4] / apply(result$eqq2,2,sd)[1], 
               apply(result$eqq3,2,sd)[2:4] / apply(result$eqq3,2,sd)[1], 
               apply(result$eqq4,2,sd)[2:4] / apply(result$eqq4,2,sd)[1], 
               apply(result$eqq5,2,sd)[2:4] / apply(result$eqq5,2,sd)[1], 
               apply(result$eqq6,2,sd)[2:4] / apply(result$eqq6,2,sd)[1],
               apply(result$eqq7,2,sd)[2:4] / apply(result$eqq7,2,sd)[1])
  
  rownames(evv1) = c('10th', '20th', '50th', '125th', '250th', '325th', '400th')
  colnames(evv1) = c('new m()', 'Dikta1', 'Dikta2')
  
  round(evv1,4)
  
  evv_list[[i]] = evv1
}

new_m = c()
dikta1 = c()
dikta2 = c()

enew_m = c()
edikta1 = c()
edikta2 = c()

for(i in 1:5){
  new_m = cbind(new_m, vv_list[[i]][,1])
  dikta1 = cbind(dikta1, vv_list[[i]][,2])
  dikta2 = cbind(dikta2, vv_list[[i]][,3])
  
  enew_m = cbind(enew_m, evv_list[[i]][,1])
  edikta1 = cbind(edikta1, evv_list[[i]][,2])
  edikta2 = cbind(edikta2, evv_list[[i]][,3])
}


```



# Data generation 

#### CDF of the death time and censor time 

$$
S(T \geq x, C \geq y) =
\begin{cases}
e^{-\theta x}  e^{-(e^{ \theta y} - 1)\big( ( \theta x-  \theta y)^2 + 1\big)} & x \geq y \\
e^{- \theta x} e^{-(e^{ \theta y} - 1)} & x < y
\end{cases}
$$
And
$$S_T(t) = P(T > t) = P(T > t, C > 0) = e^{- \theta t}  e^{-(e^{ \theta 0} - 1)\big( (t-0)^2 + 1\big)} = e^{- \theta t}$$
$$f_T(t) = \frac{\partial}{\partial t} (1 - S_T(t)) = \frac{\partial}{\partial t} (1 - e^{-\theta t}) = \theta e^{- \theta t}$$
$$S_x(t) = P(T > t, C> t) = e^{-\theta t} e^{-(e^{ \theta t} - 1)} = e^{-e^{\theta t} - \theta t + 1}$$
$$f_x(t) = \frac{\partial}{\partial t} (1 - S_x(t)) = 1- e^{-e^{\theta t} - \theta t + 1} = \theta (1 + e^{\theta t})e^{-e^{\theta t} - \theta t + 1}$$
$$\psi(t) = \int_t^{\infty} f(t,c) dc = \int_t^{\infty} \theta^2  e^{-e^{ \theta c} +\theta c - \theta t + 1} dc = \theta e^{-e^{\theta t} - \theta t + 1}$$
Therefore, 
the $m()$ function is: 
$$m(t) = \frac{\lambda_F(t)}{\lambda_H(t)} = \frac{f_T(t)}{S_T(t)}/ \frac{f_X(t)}{S_X(t)} = \frac{\theta e^{- \theta t}}{e^{- \theta t}} / \frac{ \theta (1 + e^{\theta t})e^{-e^{\theta t} - \theta t + 1}}{e^{-e^{\theta t} - \theta t + 1}} = \frac{1}{1 + e^{\theta t}}$$
And for the $\rho()$ function, 
$$\begin{aligned}
\rho = & \frac{f(t)/\psi(t) - 1}{S(t)/S_x(t) - 1}  \\ 
= & \frac{\theta e^{-\theta t}/(\theta e^{-e^ {\theta t} - \theta t + 1}) -1}{ e^{- \theta t}/ e^{-e^{\theta t} -\theta t + 1} -1}\\
= & 1
\end{aligned}$$



#### PDF of the death time and censor time 

$$f_{T,C}(x,y)  = \begin{cases}
 ((2\theta^2  x - 2\theta^2y)(1 - e^{\theta y}) - \theta)((2 \theta^2 y-2 \theta^2 x)(1 - e^{\theta y}) - \theta (\theta^2 y^2 - 2 \theta^2 xy + \theta^2 x^2 + 1)e^{\theta y}) \times \\
 e^{(\theta^2 y^2 - 2 \theta^2 xy + \theta^2 x^2 + 1)(1 - e^{\theta y}) -\theta x} \\
  + (\theta (2 \theta^2 y - 2 \theta^2 x) e^{ \theta y} - 2 \theta^2 (1 - e^{\theta y}))e^{(\theta^2 y^2 - 2 \theta^2 xy + \theta^2 x^2 + 1)(1 - e^{\theta y}) -\theta x}  & x \geq y \\
 \\
\theta^2  e^{-e^{ \theta y} +\theta y - \theta x + 1} & x < y
\end{cases}$$

## Data generation, check margnial

For example, when theta = 1, 

```{R include =FALSE}
theta = 1
   # simulate data
  set.seed(1234)  
    # x>y
    t1 = rexp(2000,theta)
    c1 = c()
    for(i in 1:length(t1)){
      # bars = Fc_t(t1[i],t1[i])
      # xx = runif(1,0,bars)
      xx = runif(1,0,1)
      c1 = c(c1, inverse_fct(xx, t1[i]))
    }
    
    
    data1 = data.frame(death = t1, censor = c1)
    data1$time = ifelse( (data1$death < data1$censor), data1$death, data1$censor)
    data1$status = ifelse(data1$death < data1$censor, 1, 0)
    data1 = data1[(data1$time >0 & data1$status == 0), ]
    data1 = data1[sample(1:dim(data1)[1])[1:300],]
    rownames(data1) = NULL
    # when x < y
    t2 = rexp(2000, theta)
    xx = runif(2000)
    c2 = log(1 - log(1 - xx))/theta
    data2 = data.frame(death = t2, censor = c2)
    data2 = data2[(data2$death < data2$censor), ]
    data2$time = ifelse((data2$death < data2$censor), data2$death, data2$censor)
    data2$status = ifelse(data2$death < data2$censor, 1, 0)
    range(data2$time)
    rownames(data2) = NULL
    data2 = data2[(sample(1:dim(data2)[1])[1:200]),]
    rownames(data2) = NULL
    dim(data2)
    sum(data2$status)
    
    data = rbind(data1, data2)
    range(data$time)
    data = data[order(data$time),]
    rownames(data) = NULL
```

* Histogram of $T$ estimation

The red line is the true density of $T$

```{R fig.width=6, fig.height=4,echo=FALSE,  fig.align = "center"}
hist(data$death, freq = FALSE, breaks = 100, xlab = 'death time', main = NULL)
xxx = seq(0,7,0.1)
lines(xxx, exp(-xxx), col = 2)
```

* Histogram of $C$ estimation

The red line is the true density of $C$

```{R fig.width=6, fig.height=4,echo=FALSE,  fig.align = "center"}
hist(data$censor, freq = FALSE, breaks = 100, xlab = 'censor time', main = NULL)
lines(xxx, exp(-exp(xxx) + xxx + 1), col = 2)
```


#### Settings: 

$\theta = 0.8, 1, 1.5, 2, 5$

# Results

## Estimation of $\theta$ by logistic regression

```{R echo = FALSE}
the_est = matrix(the_est, 1,5)
colnames(the_est) = c(0.8, 1, 1.5, 2, 5)
rownames(the_est) = 'Estimated theta'
kable(round(the_est,4), booktabs=TRUE, "latex", align="c", longtable = T, escape = F)
```


## Estimation of $m()$ by logistic regression

Plug in the estimated $\hat \theta$ to get the estimated $\hat m(t)$. Calculate the mean absolute difference between true $m(t)$ and $\hat m(t)$.

```{R echo = FALSE}
m_est = matrix(m_est, 1,5)
colnames(m_est) = c(0.8, 1, 1.5, 2, 5)
rownames(m_est) = '|hat m(t) - m(t)|'
kable(round(m_est,4), booktabs=TRUE,"latex", align="c", longtable = T, escape = F)
```


## Estimation of $S(t)$ with true $m(t)$

```{R echo = FALSE}
colnames(m_diff) = c('KM', 'new m()', 'Dikta1', 'Dikta2')
rownames(m_diff) = c(0.8, 1, 1.5, 2, 5)
m_diff = round(m_diff,4)
kable(m_diff,booktabs=TRUE, "latex", align="c", longtable = T, escape = F)
```

## Estimation of $S(t)$ with logistic regression estimated $m(t)$

```{R echo = FALSE}
colnames(em_diff) = c('KM', 'new m()', 'Dikta1', 'Dikta2')
rownames(em_diff) = c(0.8, 1, 1.5, 2, 5)
em_diff = round(em_diff,4)
kable(em_diff, booktabs=TRUE,"latex", align="c", longtable = T, escape = F)
```


## Variances of the quantiles of $S(t)$ 

Let's look at the variance of the estimation: S(t) at the '10th', '20th', '50th', '125th', '250th', '325th', '400th' out of 500 subjects. 

The following table shows the fraction of standard deviation of new methods over Kaplan Meier estiamter: $\frac{v}{v_{km}}$. 


#### 1. Estimated by $\lambda_F(t) = m(t) \lambda_H(t)$ ($\frac{v}{v_{km}}$)

```{R echo = FALSE}
new_m = cbind(new_m, enew_m)
colnames(new_m) = c(0.8, 1, 1.5, 2, 5, 0.8, 1, 1.5, 2, 5)
new_m = round(new_m, 4)
kable(new_m, "latex", align="c", booktabs=TRUE, escape = F,  linesep = NULL, longtable = T) %>%
  add_header_above(header = c(" " = 1,
                              " With true m()" = 5,
                              " Logistic estimated m()" = 5))
```

#### 2. Estimated by Dikta's 1st formula  ($\frac{v}{v_{km}}$)
 
```{R echo = FALSE}
new_m = cbind(dikta1, edikta1)
colnames(new_m) = c(0.8, 1, 1.5, 2, 5, 0.8, 1, 1.5, 2, 5)
new_m = round(new_m, 4)
kable(new_m, "latex", align="c", booktabs=TRUE, escape = F,  linesep = NULL, longtable = T) %>%
  add_header_above(header = c(" " = 1,
                              " With true m()" = 5,
                              " Logistic estimated m()" = 5))
```

#### 3. Estimated by Dikta's 2nd formula  ($\frac{v}{v_{km}}$)

```{R echo = FALSE}
new_m = cbind(dikta2, edikta2)
colnames(new_m) = c(0.8, 1, 1.5, 2, 5, 0.8, 1, 1.5, 2, 5)
new_m = round(new_m, 4)
kable(new_m, "latex", align="c", booktabs=TRUE, escape = F, linesep = NULL,  longtable = T) %>%
  add_header_above(header = c(" " = 1, 
                              " With true m()" = 5,
                              " Logistic estimated m()" = 5))
```

## Plots of the variances

```{R fig.width=8, fig.height=4, echo=FALSE,  fig.align = "center"}

qq =qq_list[[1]]
eqq= eqq_list[[1]]
par(mfrow = c(1,2))

  plot(1:7, qq[,1], type ='l', ylim = c(0, 0.025), xaxt = "n",
       xlab = 'quantile', ylab = 'standard deviation', main = paste('theta =', theta_list[i]))
  lines(1:7, qq[,2], col = 2, lty = 2, type ='l')
  lines(1:7, qq[,3], col = 3, lty = 3, type ='l')
  lines(1:7, qq[,4], col = 4, lty = 4, type ='l')
  axis(1, at=1:7, labels= c('10th', '20th', '50th', '125th', '250th', '325th', '400th'))
  #axis(1, at=1:7, labels= c(10, 20, 50, 125, 250, 325, 400))
  legend('topleft', legend = c('KM','exp() m()', 'Dikta 1', 'Dikta2'), lty = 1:4, col = 1:4, cex = 0.9)
  
  plot(1:7, eqq[,1], type ='l', ylim = c(0, 0.025), xaxt = "n",
       xlab = 'quantile', ylab = 'standard deviation', main = paste('theta =', theta_list[i], '(logistic regression estimated)'))
  lines(1:7, eqq[,2], col = 2, lty = 2, type ='l')
  lines(1:7, eqq[,3], col = 3, lty = 3, type ='l')
  lines(1:7, eqq[,4], col = 4, lty = 4, type ='l')
  axis(1, at=1:7, labels= c('10th', '20th', '50th', '125th', '250th', '325th', '400th'))
  #axis(1, at=1:7, labels= c(10, 20, 50, 125, 250, 325, 400))
  legend('topleft', legend = c('KM','exp() m()', 'Dikta 1', 'Dikta2'), lty = 1:4, col = 1:4, cex = 0.9)
  

```


```{R fig.width=8, fig.height=4, echo=FALSE,  fig.align = "center"}

qq =qq_list[[2]]
eqq= eqq_list[[2]]

par(mfrow = c(1,2))

  plot(1:7, qq[,1], type ='l', ylim = c(0, 0.025), xaxt = "n",
       xlab = 'quantile', ylab = 'standard deviation', main = paste('theta =', theta_list[i]))
  lines(1:7, qq[,2], col = 2, lty = 2, type ='l')
  lines(1:7, qq[,3], col = 3, lty = 3, type ='l')
  lines(1:7, qq[,4], col = 4, lty = 4, type ='l')
  axis(1, at=1:7, labels= c('10th', '20th', '50th', '125th', '250th', '325th', '400th'))
  #axis(1, at=1:7, labels= c(10, 20, 50, 125, 250, 325, 400))
  legend('topleft', legend = c('KM','exp() m()', 'Dikta 1', 'Dikta2'), lty = 1:4, col = 1:4, cex = 0.9)
  
  plot(1:7, eqq[,1], type ='l', ylim = c(0, 0.025), xaxt = "n",
       xlab = 'quantile', ylab = 'standard deviation', main = paste('theta =', theta_list[i], '(logistic regression estimated)'))
  lines(1:7, eqq[,2], col = 2, lty = 2, type ='l')
  lines(1:7, eqq[,3], col = 3, lty = 3, type ='l')
  lines(1:7, eqq[,4], col = 4, lty = 4, type ='l')
  axis(1, at=1:7, labels= c('10th', '20th', '50th', '125th', '250th', '325th', '400th'))
  #axis(1, at=1:7, labels= c(10, 20, 50, 125, 250, 325, 400))
  legend('topleft', legend = c('KM','exp() m()', 'Dikta 1', 'Dikta2'), lty = 1:4, col = 1:4, cex = 0.9)
  

```



```{R fig.width=8, fig.height=4, echo=FALSE,  fig.align = "center"}

qq =qq_list[[3]]
eqq= eqq_list[[3]]
par(mfrow = c(1,2))

  plot(1:7, qq[,1], type ='l', ylim = c(0, 0.025), xaxt = "n",
       xlab = 'quantile', ylab = 'standard deviation', main = paste('theta =', theta_list[i]))
  lines(1:7, qq[,2], col = 2, lty = 2, type ='l')
  lines(1:7, qq[,3], col = 3, lty = 3, type ='l')
  lines(1:7, qq[,4], col = 4, lty = 4, type ='l')
  axis(1, at=1:7, labels= c('10th', '20th', '50th', '125th', '250th', '325th', '400th'))
  #axis(1, at=1:7, labels= c(10, 20, 50, 125, 250, 325, 400))
  legend('topleft', legend = c('KM','exp() m()', 'Dikta 1', 'Dikta2'), lty = 1:4, col = 1:4, cex = 0.9)
  
  plot(1:7, eqq[,1], type ='l', ylim = c(0, 0.025), xaxt = "n",
       xlab = 'quantile', ylab = 'standard deviation', main = paste('theta =', theta_list[i], '(logistic regression estimated)'))
  lines(1:7, eqq[,2], col = 2, lty = 2, type ='l')
  lines(1:7, eqq[,3], col = 3, lty = 3, type ='l')
  lines(1:7, eqq[,4], col = 4, lty = 4, type ='l')
  axis(1, at=1:7, labels= c('10th', '20th', '50th', '125th', '250th', '325th', '400th'))
  #axis(1, at=1:7, labels= c(10, 20, 50, 125, 250, 325, 400))
  legend('topleft', legend = c('KM','exp() m()', 'Dikta 1', 'Dikta2'), lty = 1:4, col = 1:4, cex = 0.9)
  

```



```{R fig.width=8, fig.height=4, echo=FALSE,  fig.align = "center"}

qq =qq_list[[4]]
eqq= eqq_list[[4]]
par(mfrow = c(1,2))

  plot(1:7, qq[,1], type ='l', ylim = c(0, 0.025), xaxt = "n",
       xlab = 'quantile', ylab = 'standard deviation', main = paste('theta =', theta_list[i]))
  lines(1:7, qq[,2], col = 2, lty = 2, type ='l')
  lines(1:7, qq[,3], col = 3, lty = 3, type ='l')
  lines(1:7, qq[,4], col = 4, lty = 4, type ='l')
  axis(1, at=1:7, labels= c('10th', '20th', '50th', '125th', '250th', '325th', '400th'))
  #axis(1, at=1:7, labels= c(10, 20, 50, 125, 250, 325, 400))
  legend('topleft', legend = c('KM','exp() m()', 'Dikta 1', 'Dikta2'), lty = 1:4, col = 1:4, cex = 0.9)
  
  plot(1:7, eqq[,1], type ='l', ylim = c(0, 0.025), xaxt = "n",
       xlab = 'quantile', ylab = 'standard deviation', main = paste('theta =', theta_list[i], '(logistic regression estimated)'))
  lines(1:7, eqq[,2], col = 2, lty = 2, type ='l')
  lines(1:7, eqq[,3], col = 3, lty = 3, type ='l')
  lines(1:7, eqq[,4], col = 4, lty = 4, type ='l')
  axis(1, at=1:7, labels= c('10th', '20th', '50th', '125th', '250th', '325th', '400th'))
  #axis(1, at=1:7, labels= c(10, 20, 50, 125, 250, 325, 400))
  legend('topleft', legend = c('KM','exp() m()', 'Dikta 1', 'Dikta2'), lty = 1:4, col = 1:4, cex = 0.9)
  

```



```{R fig.width=8, fig.height=4, echo=FALSE,  fig.align = "center"}

qq =qq_list[[5]]
eqq= eqq_list[[5]]
par(mfrow = c(1,2))

  plot(1:7, qq[,1], type ='l', ylim = c(0, 0.025), xaxt = "n",
       xlab = 'quantile', ylab = 'standard deviation', main = paste('theta =', theta_list[i]))
  lines(1:7, qq[,2], col = 2, lty = 2, type ='l')
  lines(1:7, qq[,3], col = 3, lty = 3, type ='l')
  lines(1:7, qq[,4], col = 4, lty = 4, type ='l')
  axis(1, at=1:7, labels= c('10th', '20th', '50th', '125th', '250th', '325th', '400th'))
  #axis(1, at=1:7, labels= c(10, 20, 50, 125, 250, 325, 400))
  legend('topleft', legend = c('KM','exp() m()', 'Dikta 1', 'Dikta2'), lty = 1:4, col = 1:4, cex = 0.9)
  
  plot(1:7, eqq[,1], type ='l', ylim = c(0, 0.025), xaxt = "n",
       xlab = 'quantile', ylab = 'standard deviation', main = paste('theta =', theta_list[i], '(logistic regression estimated)'))
  lines(1:7, eqq[,2], col = 2, lty = 2, type ='l')
  lines(1:7, eqq[,3], col = 3, lty = 3, type ='l')
  lines(1:7, eqq[,4], col = 4, lty = 4, type ='l')
  axis(1, at=1:7, labels= c('10th', '20th', '50th', '125th', '250th', '325th', '400th'))
  #axis(1, at=1:7, labels= c(10, 20, 50, 125, 250, 325, 400))
  legend('topleft', legend = c('KM','exp() m()', 'Dikta 1', 'Dikta2'), lty = 1:4, col = 1:4, cex = 0.9)
  

```


